apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-config
  labels:
    app: {{ include "helm.name" . }}-config
data:
  SERVER_API_HOST: {{ .Values.config.server.apiHost }}
  SERVER_READ_TIMEOUT: {{ .Values.config.server.readTimeout }}
  SERVER_IDLE_TIMEOUT: {{ .Values.config.server.idleTimeout }}
  SERVER_WRITE_TIMEOUT: {{ .Values.config.server.writeTimeout }}
  SERVER_SHUTDOWN_TIMEOUT: {{ .Values.config.server.shutdownTimeout }}