# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "helm.fullname" . }}-svc
# spec:
#   type: {{ .Values.metallb.service.type }}
#   selector:
#     app: {{ include "helm.name" . }}-pod
#   ports:
#     - port: {{ .Values.metallb.service.port }}
#       protocol: {{ .Values.metallb.service.protocol }}
#       targetPort: {{ .Values.deploy.port.containerPort }}
