apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-app-secrets
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: {{ include "helm.name" . }}-platform
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    environment: {{ .Values.global.environment | default "development" | lower }}
type: Opaque
data:
  DB_USER: {{ .Values.secrets.db.user | default "cG9zdGdyZXNxbA==" }}
  DB_PASSWORD: {{ .Values.secrets.db.password | default "cG9zdGdyZXNxbA==" }}