apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-api-service
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ include "helm.name" . }}
    environment: {{ .Values.global.environment | default "development" | lower }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "{{ .Values.service.port | default 80 }}"
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/component: backend-api
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ include "helm.name" . }}
    environment: {{ .Values.global.environment | default "development" | lower }}
  ports:
  - name: http
    port: {{ .Values.service.port | default 80 }}
    protocol: {{ .Values.service.protocol | default "TCP" }}
    targetPort: {{ .Values.deploy.port.containerPort | default 8080 }}