apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-prometheus-svc
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: {{ include "helm.name" . }}
    environment: {{ .Values.global.environment | default "development" | lower }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: {{ include "helm.name" . }}
    environment: {{ .Values.global.environment | default "development" | lower }}
  ports:
    - port: 9090
      name: http
      protocol: TCP
      targetPort: 9090